        button1 = tk.Button(self.root,text = 'Add client', command=self.addClient)
        button1.grid(row=3,column=1)
        button2 = tk.Button(self.root,text = 'Delete client by clientCode', command=self.deleteClient)
        button2.grid(row=4,column=1)
        button3 = tk.Button(self.root,text = 'Update client', command=self.updateClient)
        button3.grid(row=6,column=1)
        button4 = tk.Button(self.root,text = 'Read all clients', command=self.readAllClients)
        button4.grid(row=7,column=1)
        button5 = tk.Button(self.root,text = 'Read client', command=self.readClient)
        button5.grid(row=8,column=1)
